### ISSUE TITLE
cannot correct song lyrics without artist and title to fetch lyrics

### ISSUE THREAD

**Issue by Hwangkop** [nomadkaraoke/python-lyrics-transcriber#10]
I saw in the usage example that

```
transcriber = LyricsTranscriber(audio_filepath='path_to_audio.mp3')
result_metadata = transcriber.generate()
```
But when I used it like this, an exception was thrown
```
Exception: cannot correct song lyrics without artist and title to fetch lyrics
```

Does it currently not support inputting local songs like those generated by suno and generating lyrics files?

**Comment by beveradb** [comment]
Hey, sorry for the slow reply - try the newest version, I think I probably fixed that in [v0.16.3](https://github.com/karaokenerds/python-lyrics-transcriber/releases/tag/v0.16.3) or newer!
